### PR TITLE
Issue 191: Handle overflow from multiple tds independently.

### PR DESCRIPTION
**Pull request by NigelCunningham**
And ensure all tds are included on the overflow rebuild and not duplicated.

### CODE REVIEW

**Comment by EnochGao** [comment]
There are still some problems. The second row is missing
[table.txt](https://github.com/pagedjs/pagedjs/files/14739137/table.txt)

image

**Comment by NigelCunningham** [comment]
Thanks for the feedback. I'm continuing to work on this and the other issues, but have more pressing things that are taking my attention first - I've done some work on these tickets this evening but am not there yet.

**Comment by EnochGao** [comment]
When will it be fixed? It's urgent.

**Comment by NigelCunningham** [comment]
I'm sorry but I'm not getting paid to work on this so I'm doing it when I have time.

Regards,

Nigel

**Comment by NigelCunningham** [comment]
@EnochGao please try the branch on my repo: https://github.com/NigelCunningham/pagedjs/tree/Issue-191. It's not complete yet (ie not all tests are passing) but I think it should be usable for you.

**Comment by julientaq** [comment]
Thanks for your hard work @NigelCunningham really appreciated.

**Comment by EnochGao** [comment]
> @EnochGao please try the branch on my repo: https://github.com/NigelCunningham/pagedjs/tree/Issue-191. It's not complete yet (ie not all tests are passing) but I think it should be usable for you.

wow, that's great. Thank you so much for your contribution

**Comment by EnochGao** [comment]
Thank you for your contribution, but I found a new problem, table nesting paging errors
image

[tablebug.txt](https://github.com/pagedjs/pagedjs/files/14917164/tablebug.txt)

**Comment by EnochGao** [comment]
When table is set to 'break-inside: avoid;' page loss.
image
[lose.txt](https://github.com/pagedjs/pagedjs/files/14985935/lose.txt)

**Comment by EnochGao** [comment]
Your programming skills are so strong, and I want to contribute, but reading source code is too difficult for me. 🥹🥹🥹🥹

**Comment by NigelCunningham** [comment]
Sorry for my slowness - too many things competing for my attention. I've started to look at this again today and don't have a heap more to do but need to take a break.

@EnochGao , regarding your nexted tables issue, I'll look at that once I get everything else going.

**Comment by NigelCunningham** [comment]
@fchasen , @julientaq , @EnochGao : I've just pushed my latest work.

The big change in this is that rather than removing overflow from a page straight away, the code adds data tags to track the overflow that has already been calculated. This prevents reflow from messing things up. I've added some of EnochGao's scenarios to the test suites too.

**Comment by EnochGao** [comment]
Thanks for your hard work. I'll try it right away✌✌

**Comment by EnochGao** [comment]
I found a problem with paging data loss due to extreme data volume。
image

[lose.txt](https://github.com/pagedjs/pagedjs/files/15173877/lose.txt)

**Comment by NigelCunningham** [comment]
I stand to be corrected but don't think /* and */ are valid HTML comments. Try doing `<!--` and `-->`

**Comment by EnochGao** [comment]
Oh, I'm sorry. It's my mistake

**Comment by NigelCunningham** [comment]
Not a problem! I'm looking at the overflow issue now.

**Comment by fchasen** [comment]
Sorry for the delay, trying out these changes now.

**Comment by NigelCunningham** [comment]
No worries Fred. I'm working on Enoch's latest issue and so have more commits coming.

**Comment by EnochGao** [comment]
Is this bug easy to fix?

**Comment by kislyuk** [comment]
@NigelCunningham thank you so much for all your work on this. May I ask what is the state of this issue and if the code in #171 is safe to use on its own? We're facing the "loss of row on page break" issue internally and would love to use these changes to address it - is there anything I can do to help?

**Comment by NigelCunningham** [comment]
Apologies for my slowness. The code in 171 has been merged and there is additional work in this branch but I've been busy with other things and not gotten everything finished yet. I've just pushed the latest work in this branch; you could give it a test with your HTML and provide another test case if you have issues.

**Comment by EnochGao** [comment]
Thanks for your hard work @NigelCunningham .There still seems to be a problem with break-inside.
[break-inside.txt](https://github.com/pagedjs/pagedjs/files/15396887/break-inside.txt)

**Comment by NigelCunningham** [comment]
Hi @fchasen @julientaq @EnochGao and others who might be interested.

Apologies for the time it has taken to get back to this - it has unfortunately taken a backseat to looking for a job (still looking for one as I write!)

I think this is ready to go now - I've tested with the break-inside.txt in Enoch's message from 2 weeks ago and it looks to me to be working fine.

**Comment by Pmtkr** [comment]
> Hi @fchasen @julientaq @EnochGao and others who might be interested.
> 
> Apologies for the time it has taken to get back to this - it has unfortunately taken a backseat to looking for a job (still looking for one as I write!)
> 
> I think this is ready to go now - I've tested with the break-inside.txt in Enoch's message from 2 weeks ago and it looks to me to be working fine.

Thanks for all the hard work you put in!

I just downloaded your 191-Issue branch, built pagedjs and tried these two things that are breaking:

Example one:
[break-inside-modified.txt](https://github.com/user-attachments/files/15596190/break-inside-modified.txt)
This one is a modified version of @EnochGao's break-inside.  I added more placeholders to the first table row. As soon as the last placeholder text (which is commented out) is uncommented, the table breaks completely.  The first page is blank, the first table row is moved to the second page and the second table row does not exist anymore,

Example two:
[word-wrap-td-breaks-inside.txt](https://github.com/user-attachments/files/15596217/word-wrap-td-breaks-inside.txt)
This one includes a table where the first table data cell is wrapped. This causes the last table row to be split, partially showing content from the wrapped data cell on the page before the break, and the rest with the other data cells on the next page.
This is also an issue in the release version 0.4.3

**Comment by NigelCunningham** [comment]
More work added for the latest issues; please test, thanks.

**Comment by julientaq** [comment]
@NigelCunningham is the api to divide each td can be reuse to (for example) divide two flexbox or cell in a css gridz/

**Comment by Pmtkr** [comment]
@NigelCunningham I tested your latest commits. 

There seems to be an issue with tables in combination with header and footer, which causes the same issue i had in the first example on my post [here](https://github.com/pagedjs/pagedjs/pull/196#issuecomment-2150917608)
[header-footer-breaks-page-non-wrapped-td.txt](https://github.com/user-attachments/files/15743883/header-footer-breaks-page-non-wrapped-td.txt)
[header-footer-breaks-page-wrapped-td.txt](https://github.com/user-attachments/files/15743885/header-footer-breaks-page-wrapped-td.txt)
The header / footer causes the table to break completely when a page break occurs on the last table row. If we remove the header and footer, everything seems to work fine. I added two examples - one with a wrapped table data cell and one with a wrapped table data cell, just to make sure that it occurs in both cases!

**Comment by drstuggels** [comment]
Hey @NigelCunningham ,
I was trying out your Issue-196 branch (latest commit e8f4c9f). It seems that a couple TR rows go missing on page breaks.
Here's a good and clear example:
[tablebug.zip](https://github.com/user-attachments/files/15774124/tablebug.zip)

Thank you!

**Comment by AnferneeCas** [comment]
Thanks for you contributions Nigel! They are very much appreciated. I tried the latest version and it isn't working, I'm still losing rows from the table. Works fine whenever I don't have set margin for the page

**Comment by NigelCunningham** [comment]
@AnferneeCas would you please provide HTML for me to test against? I thiiiiiink I've got things working in every provided case with my latest commits; perhaps you'll find the latest work (pushed after your comment) will help?

**Comment by AnferneeCas** [comment]
Hi @NigelCunningham , thanks for getting back so quickly. I tried your latest commits and it doesn't seem to solve the missing pages. 

[missing-page-html.txt](https://github.com/user-attachments/files/15944708/missing-page-html.txt)

Output
image

I manage to bring the missing page back by moving line 440 `addedExtra = this.total != prevNumPages;` to line 423 above `prevNumPages = this.total;` in Chunker.js file, but it broke multiple tests. My assumption is that something in the `emptyBody, emptyFootnotes and emptyPage` calculations is wrong but I lack knowledge to actually understand what's going on.

Thanks again for your contributions!

**Comment by NigelCunningham** [comment]
Thanks for the reply! My latest commit fixes this.

The problem was that in deciding the code was only using the first child in the DOM (if one exists) to decide whether the body of the last rendered page is empty. It should use the whole range of children (if they exist). Your sample triggers the issue because it has the footnote content (with display:none) first, unlike any of the other test cases. I'll add it to the tests and do another push after completing this comment.

**Comment by AnferneeCas** [comment]
Thank you very much @NigelCunningham . It's working now :)

**Comment by NigelCunningham** [comment]
Awesome :) @fchasen & @julientaq , I believe I've dealt with all the issues. Please review and merge if you agree and are happy with the code. Thanks!

**Comment by AnferneeCas** [comment]
Hey @NigelCunningham, doing some more testing I found that when using the minified version of your code in puppeteer to generate a pdf there is some odd behavior.

First thing I notice is that it's adding an extra page when it's not needed. Here is an screenshot of the PDF and the HTML to replicate:  
image

[extra page (1).txt](https://github.com/user-attachments/files/15949343/extra.page.1.txt)


and then it also generates a "zoomed out" pdf where the content doesn't fit the page.
image
[zoomed out content.txt](https://github.com/user-attachments/files/15949360/zoomed.out.content.txt)


Note that the only difference between the two HTML sample is the `<p>` styling in the css `margin-top: 0pt;
margin-bottom: 7pt;` . Worth mentioning that my puppeteer setup is pretty much the same as the pagedjs cli

**Comment by NigelCunningham** [comment]
Hmm, both of those things sound like the minified version is an older version of the code - they're things I saw last night but think I addressed. Using my current version of the code, I'm also not able to reproduce them with the HTML you provided. Could I therefore get you to check that your minified version is up-to-date? If it looks like it is, let's go from there.

**Comment by AnferneeCas** [comment]
I'm already up to date with your changes and after regenerating the polyfills using `npm run build` I still get the same behavior.  It wasn't happening before your changes and I haven't made any changes to my code besides swapping the minified file.

While debugging on puppeteer I notice that the output in the browser looks fine, the issue happens when trying to manually print the content via ctrl + p or when doing it programmatically through puppeteer.

Could you share your minified version so I can compare the results please?

Here is mine [paged.polyfill.min.txt](https://github.com/user-attachments/files/15950272/paged.polyfill.min.txt)

Thanks!

**Comment by NigelCunningham** [comment]
Here's mine. 
[paged.polyfill.min.js.txt](https://github.com/user-attachments/files/15950372/paged.polyfill.min.js.txt)

**Comment by AnferneeCas** [comment]
I'm getting the same behavior :/ and they appear to be the same. I'll try the CLI locally, perhaps it's my puppeteer setup.

**Comment by NigelCunningham** [comment]
Yeah, PHPStorm says they're essentially the same - just a tiny variation in the header.

**Comment by AnferneeCas** [comment]
Thanks for the help! I'll keep you posted

**Comment by AnferneeCas** [comment]
Can confirm the latest minified file works as expected using the CLI. 

Main difference from the CLI and my setup is that the CLI uses Chrome for testing while I use Chromium. 

Need to go for now, but once I get some time I'll update my setup to use Chrome for testing and post here the results.

**Comment by NigelCunningham** [comment]
Great; thanks for the info!

**Comment by AnferneeCas** [comment]
So Chromium was not the cause of the issue. The issue is I'm creating a custom handler and using the `afterRendered` method as my callback for when the doc is ready so that I can print, this used to work before. `AfterRendered` is in the chunker section of callbacks so I'm not sure if it gets called per page or when all pages are done.

I fixed the issue by changing my code to rely on `window.PagedPolyfill.on('rendered')` as the CLI does, but this listener is not expose in the documentation.

**Comment by AnferneeCas** [comment]
After further testing I manage to lose a row from a table. Here is the HTML for replicating

[missing-row-2.txt](https://github.com/user-attachments/files/15961466/missing-row-2.txt)

image
Jumps from 8 to 10, note it's a table even though it looks like a list

During my testing I also got a console error, which prevents puppeteer from generating the document. I can't post the document to replicate the issue since it has sensitive data and I wasn't able to replicate it in a different document. 

The issue I got is the following: 

image

Seems to be caused by a text node `<p>&nbsp;</p>`

**Comment by NigelCunningham** [comment]
Can you change the text in the failing document to be completely different?

Added 2 commits that fix the missing row. Break elements need some special handling.

**Comment by AnferneeCas** [comment]
Hi @NigelCunningham, I just manage to reproduce it in a random document. 
[console error.txt](https://github.com/user-attachments/files/15962847/console.error.txt)

**Comment by AnferneeCas** [comment]
Hi @NigelCunningham, I just manage to reproduce it in a random document. 

[console log error.txt](https://github.com/user-attachments/files/15962897/console.log.error.txt)

Edit: uploaded the wrong doc lol

**Comment by NigelCunningham** [comment]
That's funny because the one you uploaded is producing the issue for me :)

**Comment by NigelCunningham** [comment]
Ok... I've added more changes that address that case. I'm not 100% sure on this though - it might need more work, or perhaps just a me with a fresh mind :) Anyway, please test and @fchasen / @julientaq , please review.

**Comment by drstuggels** [comment]
The `RepeatingTableHeadersHandler` handler doesn't work (anymore?). I investigated a little bit and I think it's because the `afterPageLayout` hook runs after the `layout` hook and therefore the `this.splitTablesRefs` is empty and no theads get repeated. What hooks should be used instead? @NigelCunningham

**Comment by MarijnMensinga** [comment]
hi @NigelCunningham, very impressive work you've done! Tables for my usecases work nicely. 
I did actually encouter a couple of other render issues that were not there before using your code:
1) the moby dick example in the repo is broken. It a bit of a weird one. It breaks every now and then on different pages it is rendering with the error: `TypeError: Cannot read properties of undefined (reading 'childNodes') at Layout.addOverflowNodes`. I noticed that in your console log the `breakNeededAt` contains an empty when it crashes
2) If a page only contains absolutely positioned elements it gets marked as empty and removed. Sample html: https://pastetext.net/oor5u1kzdp simply adding an explicit space fixes it, but finding the issue is a bit obscure. 
3) A second problem with the same sample html is the removal probably has some unwanted side-effects. The first page had a different @page css than the rest of the document content. When the cover page is removed the @page settings are inherrited by the new first page: the first chapter. So in this example: the first page has no margins. Where it should have margins, only the (removed) cover page should have no margins.

**Comment by drstuggels** [comment]
Sure! This is using the latest commit in Issue-191. The handler is in `addons.js`. 
[longtable.zip](https://github.com/user-attachments/files/15973384/longtable.zip)

This is for ensuring that the thead gets repeated on the same page, so the challenge is only to repeat it once every page:
```css
thead {
  display: table-header-group;
}
```

Thanks @NigelCunningham !

**Comment by NigelCunningham** [comment]
Thanks everyone for the feedback. @AnferneeCas , I'm going to have to ask you to stop testing soon. You find too many issues! :)

**Comment by AnferneeCas** [comment]
Hi @NigelCunningham , this time I don't bring more bugs, but a possible solution. I think the reason why I'm getting the errors I posted is because of line `1073` in `layout.js`. Specifically this one: `startOfOverflow = rangeStart = next.nextElementSibling;`. Seems like you added that code for a very specific edge case in the specs, the `table/rebuild.html` spec. I'm not sure what the piece of code is doing, but removing that line fixed all my issues.

**Comment by NigelCunningham** [comment]
:)

Yeah, I fixed one of the issues yesterday by modifying that code. I'll push the commit now. 

I'm busy with other things at the moment but will seek to come back to these issues soon.

**Comment by AnferneeCas** [comment]
Thanks @NigelCunningham !

`startOfOverflow = rangeStart = next.nextElementSibling;` still seems to be the caused of the rows missing in the second issue. I'll keep looking around and let you know if I find something

**Comment by AnferneeCas** [comment]
Hi @NigelCunningham , I hope your are doing great :)

I was testing your latest code and I find some stretched cells and there are about 2-3 rows missing after the stretched rows

image

[HTML](https://pastebin.com/61eYJYS1)

**Comment by AnferneeCas** [comment]
Hi @NigelCunningham , I believe you forgot to include the bottom padding in line `846` and `1007` in the `firstOverflowChild` and `startOfNewOverflow` functions respectively

**Comment by hrehfeld** [comment]
I have missing rows at the bottom of  a long table with this pr. (private html :/)

**Comment by barnasc** [comment]
It seems this PR has an overflow issue with code blocks, see example attached. The first overflow element is not truncated correctly, resulting in missing elements/pages after this first overflow. I started debugging the code, but I was not able to find the root cause yet. Any hints which section of the `layout.js` code might cause this is appreciated.
[overflow-broken.txt](https://github.com/user-attachments/files/16429393/overflow-broken.txt)

**Comment by AnferneeCas** [comment]
Hey guys, this PR does fix many issues, but introduces some new issue around page breaks / table breaks. I have created a "stable" version for my use but it has some broken tests, specially around footnotes. In my use case I don't need footnotes so I have ignored them. I can put up a PR with my changes on top of @NigelCunningham changes if someone is down to fix the remaining issues. 

I have added new specs but I can't include them in the PR as they contain sensible data and obfuscating the data takes a lot of time.

**Comment by NigelCunningham** [comment]
Hi @AnferneeCas . Please do go ahead and push your additional changes. Sorry for my slowness in continuing on this PR - I was thinking it was going to be merged and we'd then get on with dealing with what remains in other issues but that hasn't happened and I've gotten busy with other things (including having employment for 2 months - yay!).

**Comment by RobMayer** [comment]
So, I came across an issue #197 - I'm not entirely sure what's causing it since pagedjs falls over silently during rendering, but I pulled the branch by @NigelCunningham and built locally - it ran without issue, so you're doing *something* right >.<

**Comment by julientaq** [comment]
We discussed with @fchasen and we should try to bring it in asap.

**Comment by julientaq** [comment]
so we just got off a call, and this will be merged by september 15 or so as a beta release.

The goal will be to test with existing code and scripts working with 0.4.3 and have a month of making it work.

Then it will go to paged.js 0.5.0

**Review by fchasen — APPROVED** [review]

**Comment by fchasen** [comment]
Thanks again for this and sorry for the delay! Hopefully getting this into main now should allow us to chase down any issues in the beta.

**Comment by laxmy** [comment]
I tried the beta version. It fixed the unintended space before tables. Thank you 🙌🏽
But in my tests I am getting  this error. Looks like cssRules is Array like and does not have the item() function on it. 
Could you fix it ? 
image

**Pull request merged**
