### PR TITLE
 The last line of text from a print page is sometimes not fully visible

### LINKED ISSUE #157: The last line of text from a print page is sometimes not fully visible
When a text (e.g. a paragraph) doesn't fit the current print page we first try to add as many words as we can until we find the word that overflows. If the overflow is just before a word, we simply split the text before that word. Otherwise, if the overflow is **within** the word then we add as many letters as we can (from that word) until we find the letter that doesn't fit. Then we split before that letter.

The problem is that when we check if a letter from the overflowing word fits the page we actually check if the letter **starts** inside the current print page (we check for the top and left boundary of the letter). We should instead check if the letter is fully inside the boundaries of the current print page by looking at the bottom and right letter boundaries.

### PR DESCRIPTION
**Pull request by mflorea**
This is an attempt to fix #157. All tests are passing.

### CODE REVIEW

**Comment by julientaq** [comment]
do you have a test file for this one?
Or something we can make a test with?

**Comment by tmasabari** [comment]
I tested above fix with my library and it is working fine
Without the fix
image
After the fix
image

**Review by tmasabari — CHANGES_REQUESTED** [review]

**Comment by tmasabari** [comment]
I created a new pull request https://github.com/pagedjs/pagedjs/pull/162 accommodating all the related improvements

**Comment by fchasen** [comment]
@mflorea Thanks for this great PR, really appreciate all the comments. I'll get a new version released with this shortly.

@tmasabari Still taking a look over your updates to this, some tests are failing but only on in docker.

**Pull request merged**
