### PR TITLE
fixed break token on tr of table

### PR DESCRIPTION
**Pull request by wenbei421**
Check if it overflow, the right of Rect is bounds.right + gap + bounds.width when tr break of table,so add  || (right >= end && node.tagName === "TR")

### CODE REVIEW

**Comment by wenbei421** [comment]
before:
image

after:
image

**Comment by wenbei421** [comment]
`<ul class="long_content_list">
        <li v-for="(_, i) in Array(16).fill('')" :key="i">
          {{ `我是列表${i + 1}` }}
        </li>
      </ul>
      
      <table>
        <thead>
          <tr>
            
            <td width="200px">No</td>
            <td width="300px">Month</td>
            <td width="300px">Savings</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            
            <td>1</td>
            <td>January</td>
            <td>$100</td>
          </tr>
          <tr>
            <td>2</td>
            <td>January</td>
            <td>$100</td>
          </tr>
          <tr>
            <td>3</td>
            <td>January</td>
            <td>$100</td>
          </tr>
          <tr>
            
            <td>4</td>
            <td>January</td>
            <td>$100</td>
          </tr>
          <tr>
            
            <td>5</td>
            <td>January</td>
            <td>$100</td>
          </tr>
          <tr>
            
            <td>6</td>
            <td>January</td>
            <td>$100</td>
          </tr>
          <tr>
            
            <td>7</td>
            <td>January</td>
            <td>$100</td>
          </tr>
        </tbody>
      </table>`

`.long_content_list {
  width: 100%;
  padding: 20px;
  margin: 0 auto;
  background-color: #fff;
  li {
    padding: 16px 15px;
    margin-bottom: 4px;
    color: #333;
    text-align: center;
    background-color: #fffbfa;
    border: 1px solid #f0f0f0;
    font-size: 18px;
  }
}
table {
  width: 100%;
}

table {
  border-collapse: collapse;
}

table,
th,
td {
  border: 1px solid black;
  padding: 1px;
}

tr,
td {
  break-inside: avoid;
}`

**Comment by hrehfeld** [comment]
Works for me, fixes my regresssion.

**Comment by MathisPct** [comment]
On your screenshot, it seems that the table header is repeated throw each pages. How have you make that? Because it's not implemented in pagedjs yet isn't it?

**Comment by Simply1993** [comment]
> On your screenshot, it seems that the table header is repeated throw each pages. How have you make that? Because it's not implemented in pagedjs yet isn't it?

I support, also interested in how it was done

**Comment by kingmahendra** [comment]
I am also having this table row missing issue. Is there any solution for it? I see the pr is reverted. I tried patching your fix but it does not work in my case.

**Comment by wenbei421** [comment]
> > On your screenshot, it seems that the table header is repeated throw each pages. How have you make that? Because it's not implemented in pagedjs yet isn't it?
> 
> Also interested in how it was done @wenbei421
> 
> @MathisPct maybe you found decision?


`import { registerHandlers,Handler } from 'pagedjs'
  
class RepeatingTableHeadersHandler extends Handler {

    constructor(chunker, polisher, caller) {
        super(chunker, polisher, caller);
        this.splitTablesRefs = [];
    }

    afterPageLayout(pageElement, page, breakToken, chunker) {
        this.chunker = chunker;
        this.splitTablesRefs = [];

        if (breakToken) {
            const node = breakToken.node;
            const tables = this.findAllAncestors(node, "table");
            if (node.tagName === "TABLE") {
                tables.push(node);
            }

            if (tables.length > 0) {
                this.splitTablesRefs = tables.map(t => t.dataset.ref);

                //checks if split inside thead and if so, set breakToken to next sibling element
                let thead = node.tagName === "THEAD" ? node : this.findFirstAncestor(node, "thead");
                if (thead) {
                    let lastTheadNode = thead.hasChildNodes() ? thead.lastChild : thead;
                    breakToken.node = this.nodeAfter(lastTheadNode, chunker.source);
                }

                this.hideEmptyTables(pageElement, node);
            }
        }
    }

    hideEmptyTables(pageElement, breakTokenNode) {
        this.splitTablesRefs.forEach(ref => {
            let table = pageElement.querySelector("[data-ref='" + ref + "']");
            if (table) {
                let sourceBody = table.querySelector("tbody > tr");
                if (!sourceBody || this.refEquals(sourceBody.firstElementChild, breakTokenNode)) {
                    table.style.visibility = "hidden";
                    table.style.position = "absolute";
                    let lineSpacer = table.nextSibling;
                    if (lineSpacer) {
                        lineSpacer.style.visibility = "hidden";
                        lineSpacer.style.position = "absolute";
                    }
                }
            }
        });
    }

    refEquals(a, b) {
        return a && a.dataset && b && b.dataset && a.dataset.ref === b.dataset.ref;
    }

    findFirstAncestor(element, selector) {
        while (element.parentNode && element.parentNode.nodeType === 1) {
            if (element.parentNode.matches(selector)) {
                return element.parentNode;
            }
            element = element.parentNode;
        }
        return null;
    }

    findAllAncestors(element, selector) {
        const ancestors = [];
        while (element.parentNode && element.parentNode.nodeType === 1) {
            if (element.parentNode.matches(selector)) {
                ancestors.unshift(element.parentNode);
            }
            element = element.parentNode;
        }
        return ancestors;
    }

    // The addition of repeating Table Headers is done here because this hook is triggered before overflow handling
    layout(rendered) {
        this.splitTablesRefs.forEach(ref => {
            const renderedTable = rendered.querySelector("[data-ref='" + ref + "']");
            if (renderedTable) {
                // this event can be triggered multiple times
                // added a flag repeated-headers to control when table headers already repeated in current page.
                if (!renderedTable.getAttribute("repeated-headers")) {
                    const sourceTable = this.chunker.source.querySelector("[data-ref='" + ref + "']");
                    this.repeatColgroup(sourceTable, renderedTable);
                    this.repeatTHead(sourceTable, renderedTable);
                    renderedTable.setAttribute("repeated-headers", true);
                }
            }
        });
    }

    repeatColgroup(sourceTable, renderedTable) {
        let colgroup = sourceTable.querySelectorAll("colgroup");
        let firstChild = renderedTable.firstChild;
        colgroup.forEach((colgroup) => {
            let clonedColgroup = colgroup.cloneNode(true);
            renderedTable.insertBefore(clonedColgroup, firstChild);
        });
    }

    repeatTHead(sourceTable, renderedTable) {
        let thead = sourceTable.querySelector("thead");
        if (thead) {
            let clonedThead = thead.cloneNode(true);
            renderedTable.insertBefore(clonedThead, renderedTable.firstChild);
        }
    }

    // the functions below are from pagedjs utils/dom.js
    nodeAfter(node, limiter) {
        if (limiter && node === limiter) {
            return;
        }
        let significantNode = this.nextSignificantNode(node);
        if (significantNode) {
            return significantNode;
        }
        if (node.parentNode) {
            while ((node = node.parentNode)) {
                if (limiter && node === limiter) {
                    return;
                }
                significantNode = this.nextSignificantNode(node);
                if (significantNode) {
                    return significantNode;
                }
            }
        }
    }

    nextSignificantNode(sib) {
        while ((sib = sib.nextSibling)) {
            if (!this.isIgnorable(sib)) return sib;
        }
        return null;
    }

    isIgnorable(node) {
        return (node.nodeType === 8) || // A comment node
            ((node.nodeType === 3) && this.isAllWhitespace(node)); // a text node, all whitespace
    }

    isAllWhitespace(node) {
        return !(/[^\t\n\r ]/.test(node.textContent));
    }

}

registerHandlers(RepeatingTableHeadersHandler);

  `

**Pull request merged**
